# Dockerfile defining a minimal runtime image for the Facebook Ads MCP server.
#
# The image is intentionally lightweight (Alpine + Python) because the service
# communicates over stdio and only needs the `requests` and `mcp` libraries from
# ``requirements.txt``.  Each instruction below is annotated so future
# maintainers understand why the layer exists and how it ties back to the
# server's execution model.
# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine
WORKDIR /app

# Install dependencies required by the MCP server (mcp + requests).
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the MCP server implementation and ancillary configuration into the image.
COPY . ./

# Expose port if needed, though MCP uses stdio

# Command to run the MCP server. The Facebook token must be provided via --fb-token argument.
CMD ["python", "server.py", "--fb-token", "dummy_facebook_access_token"]
