# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Alpine's musl libc image causes pip to build certain dependencies from source,
# which fails for packages like `orjson` (a transitive dependency of `mcp`) that
# require Rust tooling. Using the glibc-based slim image provides prebuilt
# wheels and allows `pip install -r requirements.txt` to succeed during the
# Smithery build step.
FROM python:3.11-slim
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . ./

# Expose the HTTP port used when running inside Smithery containers
EXPOSE 8081

# Command to run the MCP server. The Smithery runtime injects configuration via
# the MCP_CONFIG environment variable and sets the PORT for HTTP operation.
CMD ["python", "server.py"]
